name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  zig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: zig
        run: |
          sudo snap install zig --classic --edge
          echo "::set-output name=version::$(zig version)"
          zig version

      - uses: actions/cache@v3
        with:
          path: zig-cache
          key: zig-cache-${{ steps.zig.outputs.version }}
          restore-keys: zig-cache-

      - run: zig build test
