name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  zig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo snap install zig --classic --edge
          zig version

      - uses: actions/cache@v3
        with:
          path: zig-cache
          key: zig-cache-v0
          restore-keys: zig-cache-

      - run: zig build test
